server:
    port: 8081
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        hikari:
            maxLifeTime: 600000
        password: angeloa!
        url: jdbc:mysql://212.131.189.19:30016/angeloa
        username: angeloa
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                enable_lazy_load_no_trans: true
        show-sql: true
