server:
    port: 8081
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        username: angeloa
        password: angeloa!
        url: jdbc:mysql://212.131.189.19:30016/angeloa
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
